apiVersion: v1
kind: Secret
metadata:
  name: private-repo-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: "git"
  url: "git@github.com:stasiuwa/network-monitoring.git"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDdLu94bDSO2eTK/lXk920lk6KP8FnrFNYsmRNk9uuBMQAAAJggGF96IBhf
    egAAAAtzc2gtZWQyNTUxOQAAACDdLu94bDSO2eTK/lXk920lk6KP8FnrFNYsmRNk9uuBMQ
    AAAEAmtJ+ArSVmEYmvb4QaAilgtFv68Ngz1tvClYgL+JT6Bt0u73hsNI7Z5Mr+VeT3bSWT
    oo/wWesU1iyZE2T264ExAAAAEWFyZ29jZC1kZXBsb3kta2V5AQIDBA==
    -----END OPENSSH PRIVATE KEY-----