[supervisord]
nodaemon=true

[program:suricata]
command=/usr/bin/suricata -c /etc/suricata/suricata.yaml -i eth0
autorestart=true

[program:filebeat]
command=/opt/filebeat/filebeat -e -c /opt/filebeat/filebeat.yml
autorestart=true

[program:zabbix-agent]
command=/usr/sbin/zabbix_agentd -c /etc/zabbix/zabbix_agentd.conf -f
autorestart=true