FROM zabbix/zabbix-server-pgsql:6.4-alpine

LABEL org.opencontainers.image.title="Zabbix Server"
LABEL org.opencontainers.image.description="Network monitoring server"

ENV DB_SERVER_HOST=postgres
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin