filebeat.inputs:
  - type: filestream
    id: suricata
    enabled: true
    paths:
      - /var/log/suricata/eve.json

    parsers:
      - ndjson:
          overwrite_keys: true
          add_error_key: true

    fields:
      service: suricata
    fields_under_root: true
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
setup.kibana:
  host: "host.docker.internal:5601"
output.logstash:
  hosts: ["host.docker.internal:5044"]

processors:
  - add_host_metadata: ~

logging.level: info