[supervisord]
nodaemon=true

[program:suricata]
command=/usr/bin/suricata -c /etc/suricata/suricata.yaml -i any
autostart=true
autorestart=true

[program:filebeat]
command=/opt/filebeat/filebeat -e -c /opt/filebeat/filebeat.yml
autostart=true
autorestart=true
