FROM zabbix/zabbix-web-nginx-pgsql:6.4-alpine

LABEL org.opencontainers.image.title="Zabbix Web"

ENV DB_SERVER_HOST=postgres
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV ZBX_SERVER_HOST=zabbix-server